# Generated by Django 4.1.6 on 2023-02-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_remove_book_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="new_author",
            new_name="author",
        ),
    ]
