# Generated by Django 4.1.6 on 2023-02-26 15:46

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_book_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=sorl.thumbnail.fields.ImageField(
                blank=True, null=True, upload_to="books/covers/%Y/%m/"
            ),
        ),
    ]
