# Generated by Django 4.1.6 on 2023-02-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
