# Generated by Django 4.1.6 on 2023-02-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_auto_20230205_1103"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="group",
            field=models.CharField(
                choices=[("public", "public"), ("private", "private")],
                default="private",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
