# Generated by Django 4.1.6 on 2023-02-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("posts", "0004_post_created_post_modified_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="tags.tag"
            ),
        ),
    ]
