# Generated by Django 4.1.6 on 2023-02-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_datafile_post_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="img_width",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posts/images/%Y/%m/%d/",
                width_field="img_width",
            ),
        ),
    ]
